services:
    spl-users:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '30001:30001'
        volumes:
            - db-data:/app/database
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: '4.0'
                reservations:
                    cpus: '1.0'

volumes:
    db-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./database
