// Code generated by ent, DO NOT EDIT.

package ent

import (
	"spl-users/ent/location"
	"spl-users/ent/schema"
	"spl-users/ent/user"
	"spl-users/ent/userqueue"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	locationFields := schema.Location{}.Fields()
	_ = locationFields
	// locationDescSlug is the schema descriptor for slug field.
	locationDescSlug := locationFields[0].Descriptor()
	// location.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	location.SlugValidator = locationDescSlug.Validators[0].(func(string) error)
	// locationDescValue is the schema descriptor for value field.
	locationDescValue := locationFields[1].Descriptor()
	// location.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	location.ValueValidator = locationDescValue.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRun is the schema descriptor for run field.
	userDescRun := userFields[0].Descriptor()
	// user.RunValidator is a validator for the "run" field. It is called by the builders before save.
	user.RunValidator = userDescRun.Validators[0].(func(int) error)
	// userDescVerificationDigit is the schema descriptor for verification_digit field.
	userDescVerificationDigit := userFields[1].Descriptor()
	// user.VerificationDigitValidator is a validator for the "verification_digit" field. It is called by the builders before save.
	user.VerificationDigitValidator = userDescVerificationDigit.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[15].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[16].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescExpose is the schema descriptor for expose field.
	userDescExpose := userFields[17].Descriptor()
	// user.DefaultExpose holds the default value on creation for the expose field.
	user.DefaultExpose = userDescExpose.Default.(bool)
	userqueueFields := schema.UserQueue{}.Fields()
	_ = userqueueFields
	// userqueueDescRun is the schema descriptor for run field.
	userqueueDescRun := userqueueFields[0].Descriptor()
	// userqueue.RunValidator is a validator for the "run" field. It is called by the builders before save.
	userqueue.RunValidator = userqueueDescRun.Validators[0].(func(int) error)
	// userqueueDescVerificationDigit is the schema descriptor for verification_digit field.
	userqueueDescVerificationDigit := userqueueFields[1].Descriptor()
	// userqueue.VerificationDigitValidator is a validator for the "verification_digit" field. It is called by the builders before save.
	userqueue.VerificationDigitValidator = userqueueDescVerificationDigit.Validators[0].(func(string) error)
	// userqueueDescCreatedAt is the schema descriptor for created_at field.
	userqueueDescCreatedAt := userqueueFields[2].Descriptor()
	// userqueue.DefaultCreatedAt holds the default value on creation for the created_at field.
	userqueue.DefaultCreatedAt = userqueueDescCreatedAt.Default.(func() time.Time)
	// userqueueDescUpdatedAt is the schema descriptor for updated_at field.
	userqueueDescUpdatedAt := userqueueFields[3].Descriptor()
	// userqueue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userqueue.DefaultUpdatedAt = userqueueDescUpdatedAt.Default.(func() time.Time)
	// userqueue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userqueue.UpdateDefaultUpdatedAt = userqueueDescUpdatedAt.UpdateDefault.(func() time.Time)
}
