// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"spl-users/ent/predicate"
	"spl-users/ent/userqueue"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserQueueQuery is the builder for querying UserQueue entities.
type UserQueueQuery struct {
	config
	ctx        *QueryContext
	order      []userqueue.OrderOption
	inters     []Interceptor
	predicates []predicate.UserQueue
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserQueueQuery builder.
func (uqq *UserQueueQuery) Where(ps ...predicate.UserQueue) *UserQueueQuery {
	uqq.predicates = append(uqq.predicates, ps...)
	return uqq
}

// Limit the number of records to be returned by this query.
func (uqq *UserQueueQuery) Limit(limit int) *UserQueueQuery {
	uqq.ctx.Limit = &limit
	return uqq
}

// Offset to start from.
func (uqq *UserQueueQuery) Offset(offset int) *UserQueueQuery {
	uqq.ctx.Offset = &offset
	return uqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uqq *UserQueueQuery) Unique(unique bool) *UserQueueQuery {
	uqq.ctx.Unique = &unique
	return uqq
}

// Order specifies how the records should be ordered.
func (uqq *UserQueueQuery) Order(o ...userqueue.OrderOption) *UserQueueQuery {
	uqq.order = append(uqq.order, o...)
	return uqq
}

// First returns the first UserQueue entity from the query.
// Returns a *NotFoundError when no UserQueue was found.
func (uqq *UserQueueQuery) First(ctx context.Context) (*UserQueue, error) {
	nodes, err := uqq.Limit(1).All(setContextOp(ctx, uqq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userqueue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uqq *UserQueueQuery) FirstX(ctx context.Context) *UserQueue {
	node, err := uqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserQueue ID from the query.
// Returns a *NotFoundError when no UserQueue ID was found.
func (uqq *UserQueueQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uqq.Limit(1).IDs(setContextOp(ctx, uqq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userqueue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uqq *UserQueueQuery) FirstIDX(ctx context.Context) int {
	id, err := uqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserQueue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserQueue entity is found.
// Returns a *NotFoundError when no UserQueue entities are found.
func (uqq *UserQueueQuery) Only(ctx context.Context) (*UserQueue, error) {
	nodes, err := uqq.Limit(2).All(setContextOp(ctx, uqq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userqueue.Label}
	default:
		return nil, &NotSingularError{userqueue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uqq *UserQueueQuery) OnlyX(ctx context.Context) *UserQueue {
	node, err := uqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserQueue ID in the query.
// Returns a *NotSingularError when more than one UserQueue ID is found.
// Returns a *NotFoundError when no entities are found.
func (uqq *UserQueueQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uqq.Limit(2).IDs(setContextOp(ctx, uqq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userqueue.Label}
	default:
		err = &NotSingularError{userqueue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uqq *UserQueueQuery) OnlyIDX(ctx context.Context) int {
	id, err := uqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserQueues.
func (uqq *UserQueueQuery) All(ctx context.Context) ([]*UserQueue, error) {
	ctx = setContextOp(ctx, uqq.ctx, ent.OpQueryAll)
	if err := uqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserQueue, *UserQueueQuery]()
	return withInterceptors[[]*UserQueue](ctx, uqq, qr, uqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uqq *UserQueueQuery) AllX(ctx context.Context) []*UserQueue {
	nodes, err := uqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserQueue IDs.
func (uqq *UserQueueQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uqq.ctx.Unique == nil && uqq.path != nil {
		uqq.Unique(true)
	}
	ctx = setContextOp(ctx, uqq.ctx, ent.OpQueryIDs)
	if err = uqq.Select(userqueue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uqq *UserQueueQuery) IDsX(ctx context.Context) []int {
	ids, err := uqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uqq *UserQueueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uqq.ctx, ent.OpQueryCount)
	if err := uqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uqq, querierCount[*UserQueueQuery](), uqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uqq *UserQueueQuery) CountX(ctx context.Context) int {
	count, err := uqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uqq *UserQueueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uqq.ctx, ent.OpQueryExist)
	switch _, err := uqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uqq *UserQueueQuery) ExistX(ctx context.Context) bool {
	exist, err := uqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserQueueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uqq *UserQueueQuery) Clone() *UserQueueQuery {
	if uqq == nil {
		return nil
	}
	return &UserQueueQuery{
		config:     uqq.config,
		ctx:        uqq.ctx.Clone(),
		order:      append([]userqueue.OrderOption{}, uqq.order...),
		inters:     append([]Interceptor{}, uqq.inters...),
		predicates: append([]predicate.UserQueue{}, uqq.predicates...),
		// clone intermediate query.
		sql:  uqq.sql.Clone(),
		path: uqq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Run int `json:"run,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserQueue.Query().
//		GroupBy(userqueue.FieldRun).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uqq *UserQueueQuery) GroupBy(field string, fields ...string) *UserQueueGroupBy {
	uqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserQueueGroupBy{build: uqq}
	grbuild.flds = &uqq.ctx.Fields
	grbuild.label = userqueue.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Run int `json:"run,omitempty"`
//	}
//
//	client.UserQueue.Query().
//		Select(userqueue.FieldRun).
//		Scan(ctx, &v)
func (uqq *UserQueueQuery) Select(fields ...string) *UserQueueSelect {
	uqq.ctx.Fields = append(uqq.ctx.Fields, fields...)
	sbuild := &UserQueueSelect{UserQueueQuery: uqq}
	sbuild.label = userqueue.Label
	sbuild.flds, sbuild.scan = &uqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserQueueSelect configured with the given aggregations.
func (uqq *UserQueueQuery) Aggregate(fns ...AggregateFunc) *UserQueueSelect {
	return uqq.Select().Aggregate(fns...)
}

func (uqq *UserQueueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uqq); err != nil {
				return err
			}
		}
	}
	for _, f := range uqq.ctx.Fields {
		if !userqueue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uqq.path != nil {
		prev, err := uqq.path(ctx)
		if err != nil {
			return err
		}
		uqq.sql = prev
	}
	return nil
}

func (uqq *UserQueueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserQueue, error) {
	var (
		nodes = []*UserQueue{}
		_spec = uqq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserQueue).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserQueue{config: uqq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uqq *UserQueueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uqq.querySpec()
	_spec.Node.Columns = uqq.ctx.Fields
	if len(uqq.ctx.Fields) > 0 {
		_spec.Unique = uqq.ctx.Unique != nil && *uqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uqq.driver, _spec)
}

func (uqq *UserQueueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userqueue.Table, userqueue.Columns, sqlgraph.NewFieldSpec(userqueue.FieldID, field.TypeInt))
	_spec.From = uqq.sql
	if unique := uqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uqq.path != nil {
		_spec.Unique = true
	}
	if fields := uqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userqueue.FieldID)
		for i := range fields {
			if fields[i] != userqueue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uqq *UserQueueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uqq.driver.Dialect())
	t1 := builder.Table(userqueue.Table)
	columns := uqq.ctx.Fields
	if len(columns) == 0 {
		columns = userqueue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uqq.sql != nil {
		selector = uqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uqq.ctx.Unique != nil && *uqq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uqq.predicates {
		p(selector)
	}
	for _, p := range uqq.order {
		p(selector)
	}
	if offset := uqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserQueueGroupBy is the group-by builder for UserQueue entities.
type UserQueueGroupBy struct {
	selector
	build *UserQueueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uqgb *UserQueueGroupBy) Aggregate(fns ...AggregateFunc) *UserQueueGroupBy {
	uqgb.fns = append(uqgb.fns, fns...)
	return uqgb
}

// Scan applies the selector query and scans the result into the given value.
func (uqgb *UserQueueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uqgb.build.ctx, ent.OpQueryGroupBy)
	if err := uqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserQueueQuery, *UserQueueGroupBy](ctx, uqgb.build, uqgb, uqgb.build.inters, v)
}

func (uqgb *UserQueueGroupBy) sqlScan(ctx context.Context, root *UserQueueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uqgb.fns))
	for _, fn := range uqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uqgb.flds)+len(uqgb.fns))
		for _, f := range *uqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserQueueSelect is the builder for selecting fields of UserQueue entities.
type UserQueueSelect struct {
	*UserQueueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uqs *UserQueueSelect) Aggregate(fns ...AggregateFunc) *UserQueueSelect {
	uqs.fns = append(uqs.fns, fns...)
	return uqs
}

// Scan applies the selector query and scans the result into the given value.
func (uqs *UserQueueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uqs.ctx, ent.OpQuerySelect)
	if err := uqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserQueueQuery, *UserQueueSelect](ctx, uqs.UserQueueQuery, uqs, uqs.inters, v)
}

func (uqs *UserQueueSelect) sqlScan(ctx context.Context, root *UserQueueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uqs.fns))
	for _, fn := range uqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
